/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { StringFilter } from "../../util/StringFilter";
import { RankListRelationFilter } from "../../rank/base/RankListRelationFilter";
import { SportWhereUniqueInput } from "../../sport/base/SportWhereUniqueInput";
import { UserListRelationFilter } from "../../user/base/UserListRelationFilter";

@InputType()
class TeamWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  admin?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => RankListRelationFilter,
  })
  @ValidateNested()
  @Type(() => RankListRelationFilter)
  @IsOptional()
  @Field(() => RankListRelationFilter, {
    nullable: true,
  })
  ranks?: RankListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => SportWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => SportWhereUniqueInput)
  @IsOptional()
  @Field(() => SportWhereUniqueInput, {
    nullable: true,
  })
  sport?: SportWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => UserListRelationFilter,
  })
  @ValidateNested()
  @Type(() => UserListRelationFilter)
  @IsOptional()
  @Field(() => UserListRelationFilter, {
    nullable: true,
  })
  users?: UserListRelationFilter;
}

export { TeamWhereInput as TeamWhereInput };
