/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { RankService } from "../rank.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { RankCreateInput } from "./RankCreateInput";
import { Rank } from "./Rank";
import { RankFindManyArgs } from "./RankFindManyArgs";
import { RankWhereUniqueInput } from "./RankWhereUniqueInput";
import { RankUpdateInput } from "./RankUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class RankControllerBase {
  constructor(
    protected readonly service: RankService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Rank })
  @nestAccessControl.UseRoles({
    resource: "Rank",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createRank(@common.Body() data: RankCreateInput): Promise<Rank> {
    return await this.service.createRank({
      data: {
        ...data,

        team: data.team
          ? {
              connect: data.team,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        score: true,

        team: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        winStreak: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Rank] })
  @ApiNestedQuery(RankFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Rank",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async ranks(@common.Req() request: Request): Promise<Rank[]> {
    const args = plainToClass(RankFindManyArgs, request.query);
    return this.service.ranks({
      ...args,
      select: {
        createdAt: true,
        id: true,
        score: true,

        team: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        winStreak: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Rank })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Rank",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async rank(
    @common.Param() params: RankWhereUniqueInput
  ): Promise<Rank | null> {
    const result = await this.service.rank({
      where: params,
      select: {
        createdAt: true,
        id: true,
        score: true,

        team: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        winStreak: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Rank })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Rank",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateRank(
    @common.Param() params: RankWhereUniqueInput,
    @common.Body() data: RankUpdateInput
  ): Promise<Rank | null> {
    try {
      return await this.service.updateRank({
        where: params,
        data: {
          ...data,

          team: data.team
            ? {
                connect: data.team,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          score: true,

          team: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          winStreak: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Rank })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Rank",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteRank(
    @common.Param() params: RankWhereUniqueInput
  ): Promise<Rank | null> {
    try {
      return await this.service.deleteRank({
        where: params,
        select: {
          createdAt: true,
          id: true,
          score: true,

          team: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          winStreak: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
